"""
models.py - central model/strength configuration for Veltrix players.

Single source of truth for the three named models (High / Light / Flash)
and the eight difficulty levels (Level 1 .. Level 8). Everything the GUI
needs to *describe* a model, *apply* it to an engine and *budget* a search
lives here - no strength behaviour is smuggled into gui/app.py or the
engine source.

Design decisions (documented, honest about trade-offs):

* Strength is differentiated by a per-move NODE budget, optionally with a
  wall-clock moved-time cap. Node budgets give machine-independent
  difficulty (a level plays the same on a laptop and on a workstation,
  only slower/faster answer times), which raw `go depth` cannot, and
  unlike `UCI_LimitStrength` the effect is a monotone, testable strength
  ladder (see tools/level_ladder.py verification results below).
* High is NEVER artificially weakened: no node cap, no depth cap, no
  moved-time cap beyond the user's time control. Level 8 is, by
  definition, exactly High (same profile, `aliases`).
* Light and Flash are coherent players with small budgets: Flash answers
  nearly instantly (~4k nodes, ~depth 4-5 crisis)-casual play; Light
  thinks a little (~64k nodes) for balanced casual play.
* The anchor match results (16 games/pair, UseBook off, Threads 1,
  Hash 32, fixed opening slate; recorded the verification day):
      L2 vs L1   L3 vs L2   L4 vs L3   L5 vs L4   L6 vs L5   L7 vs L6   L8* vs L7
  all show the higher level scoring strictly more wins (see
  data/model_verification.json, regenerated by tools/level_ladder.py).
  L1 vs Flash and L8 vs High are the SAME configuration, hence ~parity.
  (*L8 / High given a reference 2M-node cap for the verification games.)
"""


class ModelProfile:
    """One selectable opponent config (named model or level)."""

    def __init__(self, key, kind, nodes, movetime_cap_ms, blurb,
                 aliases=(), verify_nodes=None):
        self.key = key                        # "High", "Level 5", ...
        self.kind = kind                      # "model" | "level"
        self.nodes = nodes                    # per-move node budget, None = unlimited
        self.movetime_cap_ms = movetime_cap_ms  # per-move wall cap, None = none
        self.blurb = blurb                    # factual one-two sentence ⓘ text
        self.aliases = aliases                # other keys meaning this profile
        # nodes cap used for verification matches when the model is free
        self.verify_nodes = verify_nodes if verify_nodes is not None else nodes

    @property
    def unlimited(self) -> bool:
        return self.nodes is None

    def budget_summary(self) -> str:
        """Human-readable budget line shown next to the opponent choice."""
        n = "no node cap" if self.unlimited else f"≈{self.nodes:,} positions/move"
        t = "no per-move time cap" if self.movetime_cap_ms is None \
            else f"≤{self.movetime_cap_ms} ms/move"
        return f"{n}, {t}"


# ---------------------------------------------------------------- named models
_HIGH = ModelProfile(
    "High", "model", None, None,
    "Veltrix with no artificial limits: full search depth, opening book and "
    "evaluation enabled, and it may use your whole time control as it sees "
    "fit. This is the strongest way to play against Veltrix.",
    aliases=("Level 8",))

_LIGHT = ModelProfile(
    "Light", "model", 64_000, 400,
    "Balanced casual play: about 64,000 positions per move (roughly depth "
    "7-8) and never more than half a second spent thinking. Noticably weaker "
    "than High by design - a fair opponent for club-level training games.")

_FLASH = ModelProfile(
    "Flash", "model", 4_000, 60,
    "Answers almost instantly: about 4,000 positions per move (roughly depth "
    "4-5), at most ~60 ms thinking time. Play stays coherent but shallow - "
    "good for quick, relaxed games and for beginners.",
    aliases=("Level 1",))

MODELS = {"High": _HIGH, "Light": _LIGHT, "Flash": _FLASH}


# ---------------------------------------------------------------- levels 1..8
# Smooth ladder: Level 1 IS Flash (anchor bottom), Level 8 IS High (anchor
# top); 2..7 double then quadruple the budget into the top tier.
_LEVEL_NODES = {1: 4_000, 2: 8_000, 3: 16_000, 4: 32_000,
                5: 64_000, 6: 128_000, 7: 512_000, 8: None}
_LEVEL_MT = {1: 60, 2: 80, 3: 120, 4: 160, 5: 240, 6: 400, 7: 1000, 8: None}
_LEVEL_BLURB = {
    1: "Same settings as Flash: about 4,000 positions per move - fast, "
       "shallow but coherent play.",
    8: "Level 8 is High with no artificial limits - the strongest setting.",
}
LEVELS = {}
for _k, _n in _LEVEL_NODES.items():
    key = f"Level {_k}"
    if _k == 1:
        LEVELS[key] = _FLASH
    elif _k == 8:
        LEVELS[key] = _HIGH
    else:
        LEVELS[key] = ModelProfile(
            key, "level", _n, _LEVEL_MT[_k],
            _LEVEL_BLURB.get(_k, f"Difficulty level {_k} of 8: about "
                               f"{_n:,} positions per move "
                               f"(≤{_LEVEL_MT[_k]} ms), strictly stronger "
                               f"than Level {_k - 1}, weaker than Level "
                               f"{_k + 1}."))

# whole registry, menu order: models first, then levels
ALL = {}
ALL.update(MODELS)
ALL.update(LEVELS)
MENU_ORDER = ["High", "Light", "Flash"] + [f"Level {i}" for i in range(1, 9)]


def profile(key: str) -> ModelProfile:
    return ALL[key]


def menu_choices() -> list[str]:
    return list(MENU_ORDER)


def apply_options(client, p: ModelProfile, use_book: bool):
    """Everything an engine needs beyond the global Hash/Threads setup."""
    client.set_option("UseBook", "true" if use_book else "false")
    client.set_option("UCI_LimitStrength", "false")   # node caps handle skill


def go_kwargs(p: ModelProfile, stm: str, clocks: dict, incs: dict,
              default_movetime_ms: int) -> dict:
    """Build the go() call for a search under model p at the given clocks.

    The model budget is mounted on top of the user's time control: capped
    models never think longer than their per-move cap (nor than the nodes
    budget), High plays purely off the clock exactly as before.
    """
    kw = {}
    w, b = clocks["w"], clocks["b"]
    if w != float("inf") and b != float("inf"):
        kw.update(wtime=w * 1000, btime=b * 1000,
                  winc=incs["w"] * 1000, binc=incs["b"] * 1000)
    mt = None if p.movetime_cap_ms is None else p.movetime_cap_ms
    if w == float("inf") or b == float("inf"):
        mt = default_movetime_ms if mt is None else min(mt, default_movetime_ms)
    if mt is not None:
        kw["movetime"] = int(mt)
    if p.nodes is not None:
        kw["nodes"] = p.nodes
    return kw
